### ISSUE TITLE
Authors are missing for SEP-0010

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-SEP#58]
Authors are needed to get a DOI for the SEP. Though in this case perhaps we want the community to be the author?

**Comment by ehsteve** [comment]
If I get one more person to agree I'll go ahead and implement this. @Cadair when I tagged those people, did they necessarily get notifications? Also I could not tag Nabil for reasons I don't understand.

**Comment by kreardon** [comment]
Sounds good to me too. I did get a notification for your original message when you opened this on July 13.

**Comment by nabobalis** [comment]
Sure.
